### ISSUE TITLE
midterm-jpark.py is ready.

### ISSUE THREAD

**Issue by jagreenberg-matc** [madisoncollege-it-programs/python-scripting-jagreenberg-matc#10]

**Comment by cethenmc** [comment]
Thanks for putting in a very solid effort on this part of the midterm.  The first part I analyze is program execution.  When I enter false username and password combos three times, the third failure should render the magic word clause 25 times.  Instead, you just repeat the clause with the counter (1 pt).  Next, I look at the code.  In the future keep the author and script description at the top, right after the shebang.  No points deducted with your print inserted, but keep it in mind for the future.  On line 28, you have hardcoded the username and the password instead of comparing to the library entries (2 pts).  In lines 32 - 37, you have done more hardcoding.  Those three could have consolidated to the same if statement using the dictionary, and it would have also allowed you to get rid of lines 15 - 17 (2 pts).  Score 28/33.
