### ISSUE TITLE
READY FOR GRADING, Week3 string lab

### ISSUE THREAD

**Issue by jagreenberg-matc** [madisoncollege-it-programs/python-scripting-jagreenberg-matc#2]
In the steps where I was using formatting specifiers to put characters around a variable, the lab wanted me to surround the variable in brackets (This one for example, Output: '[++Red++]'),
I wasn't sure if it wanted me to add the brackets with formatting or just type them myself, I looked through all the week's material and did some research online and couldn't figure out how to add multiple different fill characters onto one variable so I just typed them in.

Let me know if there was a different way I was supposed to be adding the brackets, thank you!

**Comment by cethenmc** [comment]
Hi, Jack.  Please correct this assignment and reply to this issue when you have pushed your corrected script to Git Hub.  You forgot punctuation (#3), chose the wrong case (#6, #7, #14), forgot a symbol (#11), missed spaces (#12 and #13).  It may help you to download the lab's Word document so that you can count the spaces.  Please be more careful, as I will deduct points beginning in Week 4.  Thanks. ~Chris

**Comment by jagreenberg-matc** [comment]
Corrected the errors should be all good now. You're right it was much easier to tell how many spaces I needed in MS Word over Google Docs I'll keep that in mind.

Thanks!

**Comment by cethenmc** [comment]
in # 13, you still missed two single spaces. One between the deR and Green section and one between the Green and the eulB section.  Meaning between the ending bracket ("]") and the beginning bracket of the next section ("[").  I am letting this slide, as I am happy you are back to class and it would round up to 8 of 8 anyway.
