### ISSUE TITLE
Week5 File Interaction

### ISSUE THREAD

**Issue by jagreenberg-matc** [madisoncollege-it-programs/python-scripting-jagreenberg-matc#5]
Had to go in to work again this morning to let delivery people in, but I took another crack at the last step of the file interaction lab while I was stuck there and think I got it working, at least I got the correct output.

I will be back in class permanently starting next week, sorry again I've missed so much thanks for sticking with me I appreciate it!

**Comment by cethenmc** [comment]
1 and 2 are fine.  You are correct in saying # 3 needs work.  See if these hits help you, but don't spin wheels too long.  Book me for a time on Monday, and if none of those times work, then email me so we can find a mutual time. For now, recording 6 of 8 for this assignment.  Please reply to this ticket when you have pushed new changes, or if you decided you don't want to bother fixing and plan to take the 6.  Thanks. ~Chris

**Comment by cethenmc** [comment]
To add...in case, you want to try before meeting on # 3 in week 5...

Please don't hesitate to reach out on # 3. The key is to not use read() and readlines() because they were already used in problem 1 and 2 for this assignment. Also, ensure that with each line you read, you append it to a variable. This allows you to satisfy the requirement to save the entire content to a variable one line at a time.

These are huge hints, but please don't spin wheels too long with the pending midterm due Thursday night.

**Comment by cethenmc** [comment]
Any luck figuring the corrections out for this one, or were you hoping to go over tomorrow at the in person lab?

**Comment by jagreenberg-matc** [comment]
Sorry, my bad I could have sworn I already replied, I think I have a pretty good understanding of the content so I'm fine keeping the 6/8 score. Thank you.

**Comment by cethenmc** [comment]
Closing this ticket and locking in the 6 of 8.
