### ISSUE TITLE
midterm-if.py is ready.

### ISSUE THREAD

**Issue by jagreenberg-matc** [madisoncollege-it-programs/python-scripting-jagreenberg-matc#9]

**Comment by cethenmc** [comment]
All concepts you used were concepts learned in class, which was nice to see.  You reopened the file for each search which is much more intensive than desired (1 pt).  The requirement to use if/elif was not met, as you used a single if for each search string (2 pt).  Using the approach you selected, if one line had two of these strings on it, then you would have duplicated that line number in your calculation.  As we speak about the line number, you are counting it instead of extracting it (2 pt).  What would have happened if we only used even numbers, had gaps in our line number file, or did not sort the file by id number?  You did implement a typecast or conversion to using int(), but you performed it on an int data type (2 pt).  While working, you should regularly use type, so you are not casting things that don't need to be casted.  It was unnecessary when you weren't extracting the line number.  Your score on this part 26/33.
